tap 'homebrew/cask'
tap 'caskroom/versions'

brew 'ansible'
brew 'ctags'
brew 'direnv'
brew 'elixir'
brew 'erlang'
brew 'fzf'
brew 'git'
brew 'go'
brew 'nodejs'
brew 'npm'
brew 'openconnect'
cask 'phantomjs'
brew 'postgresql', service_restart: true
brew 'python'
brew 'rbenv'
brew 'redis', service_restart: true
brew 'terraform'
brew 'the_silver_searcher'
brew 'tmux'
brew 'v8'
cask 'vagrant'
cask 'virtualbox'
brew 'vim'
brew 'zsh'
brew 'asdf'
brew 'yarn'
